### ISSUE TITLE
Export via CI/CD is challenging

### ISSUE THREAD

**Issue by bitbrain** [viniciusgerevini/godot-aseprite-wizard#178]
I am using a Github workflow like so:
```yml
name: Godot CI/CD Pipeline

on: [push, pull_request]

env:
  GODOT_VERSION: "4.3"
  GODOT_STATUS: "stable"
jobs:
  import-assets:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.3
    steps:
      - uses: actions/checkout@v4
      - name: Cache import assets
        uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: Import assets
        run: godot --headless --verbose --editor --quit

  export-game:
    runs-on: ubuntu-latest
    needs: import-assets
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: install wine
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_ENV
      - name: Export Game using Godot
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}_export_templates.tpz"
          relative_project_path: "./godot"
          archive_output: true
          cache: false
          wine_path: ${{ env.WINE_PATH }}
```
but unfortunately, this causes the Aseprite files that are used as Spriteframes to not work on e.g. itch.io. I suspect this is because if I don't commit the .godot folder, the export expects the `aseprite` binary to be available at build time to make it work. There might be a workaround to use this action:
```yml
- name: Enable Aseprite for Exports
   uses: neomura/setup-aseprite-cli-action@v1.0.1
```
but due to Aseprite's license agreement, it will always build Aseprite from source (which can take 10-15 minutes per run). 

Is there a recommended solution to make `godot-aseprite-wizard` work inside Github actions?
